### ISSUE TITLE
Not compatible with aioredis 2

### ISSUE THREAD

**Issue by Skehmatics** [enchant97/quart-redis#1]
When running with aioredis 2, you immediately run into `ImportError: cannot import name 'create_redis_pool' from 'aioredis'`

See https://aioredis.readthedocs.io/en/latest/migration/

**Comment by enchant97** [comment]
Thanks for noticing this. I will migrate the project to be compatible with aioredis 2, for the moment I have added version lock to the pip requirements.

**Comment by enchant97** [comment]
@Skehmatics the latest version of quart-redis now uses aioredis 2.x.
