### ISSUE TITLE
(BUG) Redis not available in test environment

### ISSUE THREAD

**Issue by HelgeKrueger** [enchant97/quart-redis#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

When running the test below, a "quart_redis.RedisNotInitialized: Redis has not been initialized" is raised. I believe Redis should also load with the rest of the test environment.

### Expected Behavior

Test passes

### Steps To Reproduce

1. Install quart_redis, pytest, pytest-asyncio
2. save app.py, test_app.py
3. run pytest

### Environment

app.py

```python
from quart import Quart
from quart_redis import RedisHandler, get_redis

app = Quart(__name__)
app.config["REDIS_URI"] = "redis://localhost"
# override default connection attempts, set < 0 to disable
# app.config["REDIS_CONN_ATTEMPTS"] = 3
redis_handler = RedisHandler(app)

@app.route("/")
async def index():
    redis = get_redis()

    val = await redis.get("my-key")

    if val is None:
        await redis.set("my-key", "it works!")
        val = await redis.get("my-key")

    return val
```
test_app.py

```python
from app import app

async def test_app():
    async with app.test_client() as client:
        response = await client.get("/")

        assert response
```

**Comment by enchant97** [comment]
Hi @HelgeKrueger thanks for finding this issue.

startup & shutdown is setup to happen on Quart's `before_serving` and `after_serving` hooks. It seems Quart does not run these when using the test client. It appears in the [docs](https://quart.palletsprojects.com/en/latest/how_to_guides/startup_shutdown.html#testing) that you initialise the app using a pytest fixture.

If you could try this and let me know if it fixes the issue, however if it still fails to initialise, I will investigate a solution.
